import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ minHeight: "100vh", margin: 0, background: "#181a1b", color: "#fff" }}>
        <div
          style={{
            minHeight: "100vh",
            width: '100vw',
            background: "#181a1b",
            color: "#fff",
            fontFamily: 'var(--font-geist-sans)',
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
